import Head from 'next/head'
import HeadLine from '../Components/HeadLine/HeadLine'
import BannerHome from '../Components/Home/BannerHome'
import Welcome from '../Components/Home/Welcome'
import IBVision from '../Components/IBVision/IBVision'
import RoadMap from '../Components/RoadMap/RoadMap'
import Team from '../Components/Team/Team'
import TheSpecs from '../Components/TheSpecs/TheSpecs'

export default function Home() {
  return (
    <div>
      <Head>
        <title>infected Bodies</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <BannerHome />
      <Welcome />
      <HeadLine />
      <TheSpecs />
      <HeadLine />
      <RoadMap />
      <HeadLine />
      <IBVision />
      <HeadLine />
      <Team />
      <HeadLine />

    </div>
  )
}
